wrapper:
  config_file_name: avia.yaml
  lidar_topic: /livox/lidar
  imu_topic: /livox/imu
  lidar_type: 0 # 0)avia

front_end:
  extrin_r: [1,0,0,
            0,1,0,
            0,0,1]
  extrin_t: [0.4165,0.2326,-0.2840]
  use_inv: 1
  trajectory_save: true
  trajectory_save_file: m2dgr_street05.txt
ieskf:
  cov_gyroscope: 0.1
  cov_acceleration: 0.1
  cov_bias_acceleration: 0.0001
  cov_bias_gyroscope: 0.0001
